
name: ğŸ³ deploy

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version: "24"

    - run: npm ci
    - run: npm run build -s
    - run: npm test

    - name: ğŸ¦ move stuff around
      run: |
        rm x/client/s # delete symlink
        cp -r s x/client/s

    - name: ğŸ¦ setup ssh
      uses: webfactory/ssh-agent@v0.9.1
      with:
        ssh-private-key: ${{ secrets.SHRIMPLE_DEPLOYER_KEY }}

    - name: ğŸ¦ upload
      run: |
        rsync --delete -hamz \
          --exclude "/.git" \
          --exclude "/db" \
          --exclude "/node_modules" \
          -e "ssh -o StrictHostKeyChecking=no" \
          ./ deployer@shrimple.io:/home/deployer/app/

    - name: ğŸ¦ deploy script
      run: |
        ssh \
          -o StrictHostKeyChecking=no \
          deployer@shrimple.io \
          "/home/deployer/app/s/server/deploy.bash"

